### ISSUE TITLE
Submission to BioC

### ISSUE THREAD

**Issue by smped** [mikelove/fastqcTheoreticalGC#1]
Hi Mike,

I'm in the process of submitting a package (https://github.com/UofABioinformaticsHub/ngsReports) to Bioconductor which depends on this package. Clearly this causes a build failure on the Bioconductor tests as it lives in git, not CRAN/Bioconductor, and I'm trying to think of a workaround. The function in question is at https://github.com/UofABioinformaticsHub/ngsReports/blob/master/R/gcFromFasta.R

The two obvious ideas I've had are:

1. The `fastqcTheoreticalGC` package is also submitted to BioC
2. We include your function `generateDistn()` as part of our package with appropriate attribution

Do you have any thoughts on this or some better suggestions?

Cheers,

Steve

**Comment by mikelove** [comment]
Please feel free to include/modify this script in your package :-)
